//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.21 at 01:26:30 PM CET 
//


package _int.esa.eo.ngeo.iicd_d_ws._1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{http://ngeo.eo.esa.int/iicd-d-ws/1.0}error"/>
 *         &lt;sequence>
 *           &lt;element name="name">
 *             &lt;simpleType>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;/restriction>
 *             &lt;/simpleType>
 *           &lt;/element>
 *           &lt;element name="MonitoringStatus">
 *             &lt;simpleType>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                 &lt;enumeration value="IN_PROGRESS"/>
 *                 &lt;enumeration value="COMPLETED"/>
 *                 &lt;enumeration value="PAUSED"/>
 *                 &lt;enumeration value="CANCELLED"/>
 *               &lt;/restriction>
 *             &lt;/simpleType>
 *           &lt;/element>
 *           &lt;element name="ProductAccessList" minOccurs="0">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="ProductAccess" maxOccurs="unbounded" minOccurs="0">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element ref="{http://ngeo.eo.esa.int/iicd-d-ws/1.0}ProductAccessURL"/>
 *                               &lt;element name="ProductAccessStatus" type="{http://ngeo.eo.esa.int/iicd-d-ws/1.0}productAccessStatusType"/>
 *                               &lt;element name="DownloadNotified" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *                               &lt;element name="ProductDownloadDirectory" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/sequence>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "error",
    "name",
    "monitoringStatus",
    "productAccessList"
})
@XmlRootElement(name = "DataAccessMonitoring-Resp")
public class DataAccessMonitoringResp {

    protected Error error;
    protected String name;
    @XmlElement(name = "MonitoringStatus")
    protected String monitoringStatus;
    @XmlElement(name = "ProductAccessList")
    protected DataAccessMonitoringResp.ProductAccessList productAccessList;

    /**
     * Gets the value of the error property.
     * 
     * @return
     *     possible object is
     *     {@link Error }
     *     
     */
    public Error getError() {
        return error;
    }

    /**
     * Sets the value of the error property.
     * 
     * @param value
     *     allowed object is
     *     {@link Error }
     *     
     */
    public void setError(Error value) {
        this.error = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the monitoringStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMonitoringStatus() {
        return monitoringStatus;
    }

    /**
     * Sets the value of the monitoringStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMonitoringStatus(String value) {
        this.monitoringStatus = value;
    }

    /**
     * Gets the value of the productAccessList property.
     * 
     * @return
     *     possible object is
     *     {@link DataAccessMonitoringResp.ProductAccessList }
     *     
     */
    public DataAccessMonitoringResp.ProductAccessList getProductAccessList() {
        return productAccessList;
    }

    /**
     * Sets the value of the productAccessList property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataAccessMonitoringResp.ProductAccessList }
     *     
     */
    public void setProductAccessList(DataAccessMonitoringResp.ProductAccessList value) {
        this.productAccessList = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ProductAccess" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element ref="{http://ngeo.eo.esa.int/iicd-d-ws/1.0}ProductAccessURL"/>
     *                   &lt;element name="ProductAccessStatus" type="{http://ngeo.eo.esa.int/iicd-d-ws/1.0}productAccessStatusType"/>
     *                   &lt;element name="DownloadNotified" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
     *                   &lt;element name="ProductDownloadDirectory" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "productAccess"
    })
    public static class ProductAccessList {

        @XmlElement(name = "ProductAccess")
        protected List<DataAccessMonitoringResp.ProductAccessList.ProductAccess> productAccess;

        /**
         * Gets the value of the productAccess property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the productAccess property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getProductAccess().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DataAccessMonitoringResp.ProductAccessList.ProductAccess }
         * 
         * 
         */
        public List<DataAccessMonitoringResp.ProductAccessList.ProductAccess> getProductAccess() {
            if (productAccess == null) {
                productAccess = new ArrayList<DataAccessMonitoringResp.ProductAccessList.ProductAccess>();
            }
            return this.productAccess;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element ref="{http://ngeo.eo.esa.int/iicd-d-ws/1.0}ProductAccessURL"/>
         *         &lt;element name="ProductAccessStatus" type="{http://ngeo.eo.esa.int/iicd-d-ws/1.0}productAccessStatusType"/>
         *         &lt;element name="DownloadNotified" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
         *         &lt;element name="ProductDownloadDirectory" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "productAccessURL",
            "productAccessStatus",
            "downloadNotified",
            "productDownloadDirectory"
        })
        public static class ProductAccess {

            @XmlElement(name = "ProductAccessURL", required = true)
            @XmlSchemaType(name = "anyURI")
            protected String productAccessURL;
            @XmlElement(name = "ProductAccessStatus", required = true)
            protected ProductAccessStatusType productAccessStatus;
            @XmlElement(name = "DownloadNotified")
            @XmlSchemaType(name = "dateTime")
            protected XMLGregorianCalendar downloadNotified;
            @XmlElement(name = "ProductDownloadDirectory")
            protected String productDownloadDirectory;

            /**
             * Gets the value of the productAccessURL property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getProductAccessURL() {
                return productAccessURL;
            }

            /**
             * Sets the value of the productAccessURL property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setProductAccessURL(String value) {
                this.productAccessURL = value;
            }

            /**
             * Gets the value of the productAccessStatus property.
             * 
             * @return
             *     possible object is
             *     {@link ProductAccessStatusType }
             *     
             */
            public ProductAccessStatusType getProductAccessStatus() {
                return productAccessStatus;
            }

            /**
             * Sets the value of the productAccessStatus property.
             * 
             * @param value
             *     allowed object is
             *     {@link ProductAccessStatusType }
             *     
             */
            public void setProductAccessStatus(ProductAccessStatusType value) {
                this.productAccessStatus = value;
            }

            /**
             * Gets the value of the downloadNotified property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getDownloadNotified() {
                return downloadNotified;
            }

            /**
             * Sets the value of the downloadNotified property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setDownloadNotified(XMLGregorianCalendar value) {
                this.downloadNotified = value;
            }

            /**
             * Gets the value of the productDownloadDirectory property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getProductDownloadDirectory() {
                return productDownloadDirectory;
            }

            /**
             * Sets the value of the productDownloadDirectory property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setProductDownloadDirectory(String value) {
                this.productDownloadDirectory = value;
            }

        }

    }

}
