//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.21 at 01:26:30 PM CET 
//


package _int.esa.eo.ngeo.iicd_d_ws._1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the _int.esa.eo.ngeo.iicd_d_ws._1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ProductAccessURL_QNAME = new QName("http://ngeo.eo.esa.int/iicd-d-ws/1.0", "ProductAccessURL");
    private final static QName _DownloadManagerId_QNAME = new QName("http://ngeo.eo.esa.int/iicd-d-ws/1.0", "DownloadManagerId");
    private final static QName _DownloadManagerSetTime_QNAME = new QName("http://ngeo.eo.esa.int/iicd-d-ws/1.0", "DownloadManagerSetTime");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: _int.esa.eo.ngeo.iicd_d_ws._1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DataAccessMonitoringResp }
     * 
     */
    public DataAccessMonitoringResp createDataAccessMonitoringResp() {
        return new DataAccessMonitoringResp();
    }

    /**
     * Create an instance of {@link DataAccessMonitoringResp.ProductAccessList }
     * 
     */
    public DataAccessMonitoringResp.ProductAccessList createDataAccessMonitoringRespProductAccessList() {
        return new DataAccessMonitoringResp.ProductAccessList();
    }

    /**
     * Create an instance of {@link Error }
     * 
     */
    public Error createError() {
        return new Error();
    }

    /**
     * Create an instance of {@link DataAccessMonitoringResp.ProductAccessList.ProductAccess }
     * 
     */
    public DataAccessMonitoringResp.ProductAccessList.ProductAccess createDataAccessMonitoringRespProductAccessListProductAccess() {
        return new DataAccessMonitoringResp.ProductAccessList.ProductAccess();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ngeo.eo.esa.int/iicd-d-ws/1.0", name = "ProductAccessURL")
    public JAXBElement<String> createProductAccessURL(String value) {
        return new JAXBElement<String>(_ProductAccessURL_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ngeo.eo.esa.int/iicd-d-ws/1.0", name = "DownloadManagerId")
    public JAXBElement<String> createDownloadManagerId(String value) {
        return new JAXBElement<String>(_DownloadManagerId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ngeo.eo.esa.int/iicd-d-ws/1.0", name = "DownloadManagerSetTime")
    public JAXBElement<XMLGregorianCalendar> createDownloadManagerSetTime(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_DownloadManagerSetTime_QNAME, XMLGregorianCalendar.class, null, value);
    }

}
